### ISSUE TITLE
DIP: Timeline & Milestones Due: 01/26

### ISSUE THREAD

**Issue by juliaparish** [MEDSsnowtoday/snowtoday_capstone#12]
Lead: Marie
Review: Julia, Ryan

- [x] create visual of Timeline in Tableau
- [x] draft timeline in gantt chart
- [x] draft milestones
- [x] present to class 01/26 
- [x] review timeline w/ client
- 1. 1st pass 01/18
- 2. 2nd pass 01/24

**Notes:** draft a timeline for your work (unrelated to Bren deliverables - this should be specifically for your data science product work). Review timeline with advisor / client this week or next.

Milestones will help students complete their Capstone Project by identifying key tasks and products that they will create as the project proceeds. In this section, students should make a timeline of the dates by which they intend to complete each of the tasks outlined in the Approach and Methods section, including data acquisition, analyses, evaluation of results, product development, and testing and
documentation. Include the dates by which the group intends to complete drafts and final versions of each of its products and deliverables. _**At the end of Winter Quarter, students should review and possibly re-organize the remaining milestones.**_
